language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
# sudo: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Roaring"); Pkg.test("Roaring"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Roaring")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("Roaring")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("Roaring")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
